generators:
  diamond:
    block: DIAMOND_BLOCK
    items:
      - item: DIAMOND
        amount: 1
        chance: 100.0
    interval: 60  # seconds between generations
    max_crafts: 2  # Limit to 5 crafts per player; -1 for unlimited
    permission: itemgen.use.diamond
    recipe:
      shape:
        - 'GGG'
        - 'GDG'
        - 'GGG'
      ingredients:
        G: GOLD_INGOT
        D: DIAMOND
  iron:
    block: IRON_BLOCK
    items:
      - item: IRON_INGOT
        amount: 5
        chance: 100.0
    interval: 30
    max_crafts: 2  # Limit to 5 crafts per player; -1 for unlimited
    permission: itemgen.use.iron
    recipe:
      shape:
        - 'III'
        - 'ISI'
        - 'III'
      ingredients:
        I: IRON_INGOT
        S: STONE